### GET request to example server
GET http://localhost:8080//api/recommendation/search
    ?topic=Spassbad mit Wasserrutsche&cities=Murten,Schalunen,Schaffhausen,Basel,Zürich,Bern,Genf, Thun&maxResult=10

###